package com.mycompany.myapp;

import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Display;
import com.codename1.ui.FontImage;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.animations.CommonTransitions;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.layouts.LayeredLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.util.UITimer;
import java.io.IOException;
import com.codename1.ui.Toolbar;
import com.mycompany.Entity.Users;
import com.mycompany.gui.BudgetPieChart;
import com.mycompany.gui.CategoriesList;
import com.mycompany.gui.ChartDemosForm;
import com.mycompany.gui.HomeForm;
import com.mycompany.gui.InboxForm;
import com.mycompany.gui.Login;
import com.mycompany.gui.MapForm;
import com.mycompany.gui.ProductAdd;
import com.mycompany.gui.ProductsList;
import com.mycompany.gui.SalesBarChart;
import com.mycompany.gui.ShowBrand;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;
    public static Users user = null;
    public static String urlUpload = "http://localhost/cupcake/uploads/";
    
    public Resources getTheme() {
        return theme;
    }
    public void setTheme(Resources t)
    {
    theme=t;
    }

    public void init(Object context) {
        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature, uncomment if you have a pro subscription
        // Log.bindCrashProtection(true);
    }
    
    public void start() throws IOException {
        if(current != null){
            current.show();
            return;
        }
         /*HomeForm h = new HomeForm();
        h.getF().show();*/
                 //new ShowBrand(theme).show();
                 //new MapForm(theme).show();
                  //BudgetPieChart demos = new BudgetPieChart();
             /*SalesBarChart demos = new SalesBarChart();

        demos.execute().show();*/
        Login h = new Login();
        h.getF().show();
        
        //ProductsList f = new ProductsList();
        //CategoriesList f = new CategoriesList();
        //ProductAdd f = new ProductAdd();
        //f.getF().show();
    }

    public void stop() {
        current = Display.getInstance().getCurrent();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = Display.getInstance().getCurrent();
        }
    }
    
    public void destroy() {
    }

}
